---
title: "A New Measurement of Educational Social Mobility: Application to a Global Dataset"
author: "Khanh Duong"
date: "`r Sys.Date()`"
output: slidy_presentation
widescreen: true
duration: 45
incremental: true
self-contained: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)

# Load necessary libraries
library(ggplot2)
library(tidyr)
library(dplyr)
library(ggrepel)
library(kableExtra)
library(reshape2)
library(RColorBrewer)
library(gridExtra)

```

```{r cleaning}

Dt <- read.csv("GDIM_2023_03.csv", stringsAsFactors=TRUE)

Dt$year <- as.factor(Dt$year)
Dt$cohort <- as.factor(Dt$cohort)

Dt <- Dt %>%
  filter(cohort == "1980", parent == "max", child == "all") %>%
  rename(
    AHMP = CAT_ISCED0,
    MU050 = MU050_randomtiebreak,
    BHQ4 = BHQ4_randomtiebreak
  ) %>%
  mutate(`1-BETA` = 1 - BETA)


upward <- c("C2P1", "C3P1", "C3P2", "C4P1", "C4P2", "C4P3", "C5P1", "C5P2", "C5P3", "C5P4")
persistence <- c("C1P1","C2P2","C3P3","C4P4","C5P5")


Q_df <- data.frame(
  C1P1 = Dt$tm11 * Dt$P1, C2P1 = Dt$tm12 * Dt$P1, C3P1 = Dt$tm13 * Dt$P1, C4P1 = Dt$tm14 * Dt$P1, C5P1 = Dt$tm15 * Dt$P1,
  C1P2 = Dt$tm21 * Dt$P2, C2P2 = Dt$tm22 * Dt$P2, C3P2 = Dt$tm23 * Dt$P2, C4P2 = Dt$tm24 * Dt$P2, C5P2 = Dt$tm25 * Dt$P2,
  C1P3 = Dt$tm31 * Dt$P3, C2P3 = Dt$tm32 * Dt$P3, C3P3 = Dt$tm33 * Dt$P3, C4P3 = Dt$tm34 * Dt$P3, C5P3 = Dt$tm35 * Dt$P3,
  C1P4 = Dt$tm41 * Dt$P4, C2P4 = Dt$tm42 * Dt$P4, C3P4 = Dt$tm43 * Dt$P4, C4P4 = Dt$tm44 * Dt$P4, C5P4 = Dt$tm45 * Dt$P4,
  C1P5 = Dt$tm51 * Dt$P5, C2P5 = Dt$tm52 * Dt$P5, C3P5 = Dt$tm53 * Dt$P5, C4P5 = Dt$tm54 * Dt$P5, C5P5 = Dt$tm55 * Dt$P5
)

transmission <- 0.1

mobility <- data.frame(
  a = Dt$P1*(1-transmission) / (1 + Dt$P2*(1-transmission)),
  b = Dt$P2*(1-transmission) / (1 + Dt$P3*(1-transmission)),
  c = Dt$P3*(1-transmission) / (1 + Dt$P4*(1-transmission)),
  d = Dt$P4*(1-transmission))

P_df <- Q_df * 0

P_df$C1P1 <-transmission*Dt$P1
P_df$C2P2 <-transmission*Dt$P2
P_df$C3P3 <-transmission*Dt$P3
P_df$C4P4 <-transmission*Dt$P4

P_df$C5P5 <-Q_df$C5P5

P_df$C2P1 <-mobility$a
P_df$C3P1 <-mobility$a*mobility$b
P_df$C4P1 <-mobility$a*mobility$b*mobility$c
P_df$C5P1 <-mobility$a*mobility$b*mobility$c*mobility$d


P_df$C3P2 <-mobility$b
P_df$C4P2 <-mobility$b*mobility$c
P_df$C5P2 <-mobility$b*mobility$c*mobility$d

P_df$C4P3 <-mobility$c
P_df$C5P3 <-mobility$c*mobility$d


P_df$C5P4 <-mobility$d



```

```{r}

gap_df <- sqrt(Q_df) - sqrt(P_df)
gap_df$index <- rowSums(gap_df[, setdiff(names(gap_df), upward)])*1/sqrt(2) - rowSums(gap_df[, upward])*1/sqrt(2)

filtered_df <-cbind(Dt[, c("code", "country", "region_noHICgroup","obs", "CAT", "1-BETA", "MIX" )],Q_df)

filtered_df$index <- gap_df$index

filtered_df$index <- scales::rescale(filtered_df$index, to = c(0, 1))

```

```{r function}

region_colors <- setNames(brewer.pal(n = length(unique(filtered_df$region_noHICgroup)), "Set2"), 
                          unique(filtered_df$region_noHICgroup))

plot_heatmap <- function(df, index, country, title_suffix) {
  data_matrix <- t(matrix(as.numeric(df[index, ]), 5, 5))  
  colnames(data_matrix) <- paste0("C", 1:5)
  rownames(data_matrix) <- paste0("P", 1:5)

  heatmap_data <- melt(data_matrix)
  names(heatmap_data) <- c("Row", "Column", "Value")

  ggplot(heatmap_data, aes(Column, Row, fill = Value)) +
    geom_tile(color = "black", size = 0.5) +
    geom_text(aes(label = round(Value * 100, 2)), color = "black", size = 3) +
    scale_fill_gradientn(colors = colorRampPalette(c("whitesmoke", "cyan", "lightgreen", "green", "yellow", "pink", "salmon"))(100)) +
    scale_y_discrete(limits = rev(paste0("P", 1:5))) +
    theme_minimal() +
    theme(
      axis.text = element_text(size = 10), 
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      panel.grid = element_blank(), 
      legend.position = "none"
    ) +
    labs(title = paste(country, title_suffix))
}

heatmap <- function(code) {
  index <- which(filtered_df$code == code)
  country <- filtered_df[index, "country"]
  QQ <- plot_heatmap(Q_df, index, country, "(Actual)")
  PP <- plot_heatmap(P_df, index, country, "(Expected)")
  grid.arrange(QQ, PP, ncol = 2)
}

compare <- function(code1, code2) {
  index1 <- which(filtered_df$code == code1)
  country1 <- filtered_df[index1, "country"]
  relative1 <- filtered_df[index1, "1-BETA"]
  absolute1 <- filtered_df[index1, "CAT"]
  QQ1 <- plot_heatmap(Q_df, index1, country1, "") + 
    ggtitle(country1, subtitle = paste0("CAT = ", round(absolute1, 2),"; 1-BETA = ", round(relative1, 2)))
  
  index2 <- which(filtered_df$code == code2)
  country2 <- filtered_df[index2, "country"]
  relative2 <- filtered_df[index2, "1-BETA"]
  absolute2 <- filtered_df[index2, "CAT"]
  mix2 <- filtered_df[index2, "MIX"]
  QQ2 <- plot_heatmap(Q_df, index2, country2, "") + 
    ggtitle(country2, subtitle = paste0("CAT = ", round(absolute2, 2),"; 1-BETA = ", round(relative2, 2)))
  
  grid.arrange(QQ1, QQ2, ncol = 2)
}

analyze_gap <- function(df, a, a_label, b, b_label) {
  df <- df %>% filter(!is.na(.data[[a]]), !is.na(.data[[b]]))
  lm_fit <- lm(as.formula(paste("`", b, "` ~ `", a, "`", sep = "")), data = df)
  df$residuals <- residuals(lm_fit)
  
  # Extract regression stats
  summary_fit <- summary(lm_fit)
  slope <- formatC(coef(lm_fit)[2], format = "f", digits = 3)
  p_value <- formatC(summary_fit$coefficients[2, 4], format = "f", digits = 3)
  stat_label <- paste0("Slope = ", slope, 
                       ", P-value = ", p_value)

  # Identify outliers
  outliers_df <- bind_rows(
    df %>% filter(residuals > 0) %>% top_n(5, residuals),
    df %>% filter(residuals < 0) %>% top_n(-5, residuals),
    df %>% top_n(5, .data[[b]]),
    df %>% top_n(-5, .data[[b]])
  ) %>% distinct(country, .keep_all = TRUE)
  
  # Generate plot
  plot <- ggplot(df, aes(x = .data[[a]], y = .data[[b]])) +
    geom_point(aes(color = region_noHICgroup), size = 3, alpha = 0.7) +
    geom_smooth(method = "lm", se = FALSE, color = "black", linetype = "dashed") +
    geom_text_repel(data = outliers_df, aes(label = country), vjust = -1, size = 4, color = "black") +
    scale_color_manual(name = "Regions", values = region_colors) +
    labs(x = a_label, y = b_label, subtitle = stat_label) +
    theme_bw() + theme(plot.subtitle = element_text(hjust = 0)) +
    theme(plot.caption = element_text(hjust = 0))  # left-align caption

  return(plot)
}



```

```{r fig.height=7, fig.width=12}
abs_rel <- analyze_gap(filtered_df, "1-BETA", "Relative Mobility", "CAT", "Absolute Mobility")
rel_pro <- analyze_gap(filtered_df, "1-BETA", "Relative Mobility", "index", "Progress Gap") + ggtitle("A. Compared to Relative Mobility")
abs_pro <- analyze_gap(filtered_df, "CAT", "Absolute Mobility", "index", "Progress Gap") + ggtitle("B. Compared to Absolute Mobility")

internal <- grid.arrange(rel_pro, abs_pro, ncol = 1)


```

```{r fig.height=4, fig.width=8}
compare1 <- compare("BDI","CAF") 

```



```{r fig.height=4, fig.width=8}
compare2 <- compare("CAN","TLS")
```


```{r fig.height=4, fig.width=8}
compare3 <- compare("BTN","ISL")
```

```{r fig.height=4, fig.width=8}
compare4 <- compare("BFA","TUV")
```

```{r fig.height=8, fig.width=8}
VNM <- heatmap("VNM")
USA <- heatmap("USA")
VNM_USA <- grid.arrange(heatmap("VNM"), USA, ncol = 1)

```

```{r}
c1 <- compare("CHN","CHE") 
c3 <- compare("FIN","FRA") 
c2 <- compare("GBR","USA") 

main <- grid.arrange(c1, c2, c3, ncol = 1)

```

After this, the heatmap render  incorrectly due to changes in the ordering of countries.

# Ranking country in terms of Progress Gap

```{r ranking, fig.height=10, fig.width=20}
library(ggplot2)

# Rank the data by 'index'
filtered_df <- filtered_df[order(filtered_df$index), ]

# Ensure 'country' is a factor with levels sorted by 'index' (to maintain order in the plot)
filtered_df$country <- factor(filtered_df$country, levels = filtered_df$country)

# Divide into 3 equal groups based on index ranking
filtered_df$group <- cut(filtered_df$index, 
                         breaks = quantile(filtered_df$index, probs = seq(0, 1, length.out = 4), na.rm = TRUE),
                         labels = c("Part 1", "Part 2", "Part 3"),
                         include.lowest = TRUE)

# Generate the plot with facet_wrap() based on the new group variable
rank <- ggplot(filtered_df, aes(x = country)) + 
  geom_col(aes(y = index, fill = region_noHICgroup), position = "dodge", alpha = 0.7, show.legend = TRUE) +
  geom_point(aes(y = CAT, color = "Absolute Mobility"), size = 2, shape = 15) +
  geom_point(aes(y = `1-BETA`, color = "Relative Mobility"), size = 2, shape = 16) +
  scale_fill_manual(name = "Progress Gap by Regions", values = region_colors) +
  scale_color_manual(name = "Measurements", 
                     values = c("Absolute Mobility" = "dodgerblue3", 
                                "Relative Mobility" = "red")) +
  labs(y = "", x = "", title = "", fill = "Regions") +
  theme_bw() + 
  coord_flip() +
  facet_wrap(~ group, scales = "free_y", ncol = 3)  # Split the plot into 3 parts

# Print the plot
print(rank)


```

```{r global_map, fig.height=5, fig.width=12}

library(rnaturalearth)
library(rnaturalearthdata)
world_map <- ne_download(scale = 110, type = "countries", category = "cultural")
world_data <- left_join(world_map, filtered_df, by = c("ADM0_A3" = "code"))

map <- ggplot(world_data) +
  geom_sf(aes(fill = index)) +
  scale_fill_gradientn(
    colors = c("green", "cyan", "salmon"),  # Define three colors for the gradient
    name = "Progress Gap"
  ) +
  theme_void()
```
```{r}
library(readxl)
SPI <- read_excel("Social_Progress_Index.xlsx")
SPI_data <- left_join(filtered_df, SPI, by = c("code" = "Code"))
SPI_data$access <- SPI_data$`Access to Advanced Education`

SPI_data$Opportunity_norm <- (SPI_data$Opportunity - min(SPI_data$Opportunity, na.rm = TRUE)) /(max(SPI_data$Opportunity, na.rm = TRUE) - min(SPI_data$Opportunity, na.rm = TRUE))

SPI_data$access_norm <- (SPI_data$access - min(SPI_data$access, na.rm = TRUE)) /          (max(SPI_data$access, na.rm = TRUE) - min(SPI_data$access, na.rm = TRUE))


SPI_1 <- analyze_gap(SPI_data, "Opportunity_norm", "Opportunity", "index", "Progress Gap") + ggtitle("A. Opportunity")

SPI_2 <- analyze_gap(SPI_data, "access_norm", "Access to Advanced Education", "index", "Progress Gap") + ggtitle("B. Access to Advanced Education")

external <- grid.arrange(SPI_1, SPI_2, ncol = 1)




```



# Export

```{r}

ggsave(file="figs/internal.pdf", plot=internal, width=12, height=10)
ggsave(file="figs/external.pdf", plot=external, width=12, height=10)

ggsave(file="figs/VNM_USA.pdf", plot=VNM_USA, width=8, height=8)

ggsave(file="figs/main.pdf", plot=main, width=8, height=12)

ggsave(file="figs/compare1.pdf", plot=compare1, width=8, height=4)
ggsave(file="figs/compare2.pdf", plot=compare2, width=8, height=4)
ggsave(file="figs/compare3.pdf", plot=compare3, width=8, height=4)
ggsave(file="figs/compare4.pdf", plot=compare4, width=8, height=4)

ggsave(file="figs/rank.pdf", plot=rank, width=18, height=12)

ggsave(file="figs/map.pdf", plot=map, width=12, height=5)

write.csv(filtered_df, "tables/output.csv", row.names = FALSE)
```
